name: Deliver Tokens To Consumer

on:
  push:
    paths:	
      - 'build/**'

      
jobs:
  deliver_to_mono_universe:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Deliver Platform Deliverable To Target Application
          uses: andstor/copycat-action@v3
          with:
            # See documentation: https://docs.github.com/en/actions/reference/encrypted-secrets
            # Set the secret in the "src" repository
            personal_token: ${{ secrets.MONO_DESIGN_TOKENS_ENGINE_API_TOKEN }}
            # This is the branch that has the code for this article
            src_branch: mono-design-tokens-engine
            src_path: build/json/_variables.json
            dst_owner: ratneshmurugesan
            dst_repo_name: mono-universe
            dst_branch: develop
            dst_path: libs/design-system/shared/_variables.json
            username: ratneshmurugesan
            email: ratnesh.one@gmail.com
            commit_message: Update platform deliverable