name: Auto generate tokens on figma-tokens-plugin-git-push
on: 
  push:
    paths:
      - "src/tokens/figma-tokens.json"

jobs:
  generate_tokens:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: '16'
      - name: Install Node Dependencies
        run: yarn
      - name: Build style-dictionary
        run: yarn run build
      - name: Commit generated platform deliverables
        id: "auto-commit-action"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update platform deliverables